[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ['*']
optimizer = true
optimizer_runs = 200
solc_version = "0.8.10"
fuzz_runs = 300

[profile.fuzzing]
fuzz_runs = 20000

[rpc_endpoints]
mainnet = "${RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/gakonst/foundry/tree/master/config