[default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ['*']
optimizer = true
optimizer_runs = 200
solc_version = "0.8.10"
fuzz_runs = 300

[fuzzing]
fuzz_runs = 10000

# See more config options https://github.com/gakonst/foundry/tree/master/config