name: Slither Static Analysis

# Runs the test on every Sunday at 12am GMT
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopend, synchronize, ready_for_review ]

  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    env:
      commit_url: ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/

    steps:
      - uses: actions/checkout@v3

      - name: Run Slither
        uses: tlvince/slither-action@2160acd392a54de83b9d650a144f8cc6d5bb9a0b
        id: slither
        continue-on-error: true
        with:
          slither-args: '--checklist --markdown-root ${{ env.commit_url }}'
      
      - name: Create Slither PR Comment
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ${{ steps.slither.outputs.stdout }}
